# Generated by Django 3.0.4 on 2020-03-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataworkshop_be', '0002_auto_20200315_0813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
